=== Sebastian Lewandowski

Wstępnie w projekcie miałem zajmować się głównie implementacją części związanej z serwerem. Z przyczyn losowych
nie mogłem zbytnio uczestniczyć w początkowej fazie prac związanych z tworzeniem aplikacji.

Zadanie związane z implementacją portfela multisig w prototypie zajęło mi zdecydowanie zbyt dużo czasu.
W moim odczuciu byłem najsłabszy pod kontem stricte umiejętności programistycznych, co wynika również z faktu, że
brakuje mi komercyjnego doświadczenia w technologiach webowych. Aby nie opóźniać prac, razem z zespołem podjęliśmy
decyzję o tym, że zajmę się najłatwiejszymi zadaniami związanymi np. z testami czy też tworzeniem kolekcji w
_Postman-nie_ ze wszystkimi punktami końcowymi. Mimo to ilość czasu, jaką potrzebowałem na zrealizowanie
zagadnień oraz ilość poprawek, które musiałem nanieść była duża. Niestety ma to swoje odniesienie w
liczbie wykonanych przeze mnie zadań.

Napisałem logikę umożliwiającą usunięcie z listy administratora, który nie został jeszcze przypisany do portfela.
Połączyłem ją również z aplikacją internetową tak, aby można było wykonać tę czynność na stronie.
W aplikacji mobilnej zaimplementowałem ekran, na którym wyświetlane są szczegóły powiadomienia, takie jak: id czy też
adres. Dodałem również dwa guziki, służące do akceptowania i odrzucania transakcji.
W ramach zadania LP-135 stworzyłem testy E2E. Napisałem w języku _Gherkin_ scenariusze testowe dla przypadków logowania
oraz rejestracji, a następnie dodałem ich implementację z wykorzystaniem  narzędzia _Cypress_.

Podjąłem próbę napisania pierwszej części rozdziału "Proces realizacji". W późniejszym etapie pomysł na rozdział uległ
zmianie, wiec pewna część pracy poszła na marne. Część z tej pracy nadal jest widoczna w opisie sprintu 1.
Napisałem ostatnią część rozdziału "Proces realizacji" obejmującego sprinty 10 - 12. Opisałem również rozdział "Testy"
dotyczący testów jednostkowych, integracyjnych oraz E2E dla serwera, aplikacji webowej oraz mobilnej.

Brałem czynny udział w _code review_ głównie rozwiązań związanych z serwerem. Sporo czasu poświęciłem na sprawdzanie
tekstów napisanych przez pozostałych członków zespołu i starałem się wyłapać w nich wszystkie błędy.

.Lista zadań, przy których pracował Sebastian w procesie implementacji.
[cols="1,9,1"]
|===
|Klucz|Nazwa|Story points
|LP-62|Investigate and implement multisig wallet in prototype|-
|LP-87|Create postman collection with all endpoints|2
|LP-139|Implement admin deletion|3
|LP-132|Add notification details component|2
|LP-135|Create auth scenarios|2
|LP-182|Write "Proces realizacji" chapter - part 3|5
|LP-171|Write "testy" chapter|3
|LP-150|Complete own contribution for Sebastian Lewandowski|1
|===

Wykonałem lub brałem udział w realizacji 8 zadań, które pokazano w tabeli 19. Łączna ich wartość wyniosła 18 punktów
historii. Ich procentowy udział w całkowitej liczbie wyniósł ok. 5%. Jest to najsłabszy wynik z całego zespołu. Ta
wartość nie uwzględnia czasu poświęconego na tworzenie dokumentacji podczas pierwszego etapu realizacji, na naukę oraz
na _code review_.
