[glossary]
== Słownik pojęć

multisig::
    Rozdaj adresu, który wymaga kilku podpisów cyfrowych, aby wykorzystać zapisane na nim środki. Jeżeli transakcja
    nie będzie podpisana przez wymaganą liczbę użytkowników, zostanie ona odrzucona przez inne węzły Bitcoina.
    <<btcbook>>

macaroon::
    Dane uwierzytelniające, które zapewniają elastyczne wsparcie dla kontrolowanego udostępniania w zdecentralizowanych
    rozproszonych systemach, takich jak sieć Lightning. Może on łączyć się z usługami i umożliwiać wykonywanie działań
    w imieniu węzła Lightning. Jest podobny do pliku cookie, ale w przeciwieństwie do tradycyjnego pliku cookie
    przeglądarki, można utworzyć makaronik o ograniczonych możliwościach, a następnie wysłać go do innych użytkowników.
    <<lnbook>>

UTXO::
    Jest to niewydane wyjście z transakcji Bitcoin. Suma wartości UTXO użytkownika mówi, ile posiada on Bitcoinów.

satoshi::
    Najmniejsza jednostka rozliczeniowa w ekosystemie Bitcoina. Można ją porównać do groszy w polskiej walucie.
    Jeden satoshi jest równowarte 0,00000001 BTC. Wszystkie operacje w sieci takie jak transakcje operują właśnie
    na wartości satoshi.

Węzeł sieci Bitcoin::
    Jest to program działający w sieci Bitcoina, który przechowuje, synchronizuje oraz sprawdza konsensus blockchaina.
    Wyróżniamy kilka rodzajów węzłów. Najczęściej spotyka się węzły pełne oraz niepełne (lekkie). Węzły pełne
    wyróżniają się tym, że przechowują kopię całego blockchaina.

Górnik::
    W kontekście sieci Bitcoin jest to program zajmujący się zbieraniem i walidacją transakcji, budowaniem bloków oraz
    liczeniem dla nich dowodu pracy. Za wykopanie bloku górnik otrzymuje nagrodę w postaci określonej liczby Bitcoinów.
    W tak zwanym "Bitcoin whitepaper <<whitepaper>>", słowo węzeł używane było jako synonim górnika, aczkolwiek
    współcześnie do kopania Bitcoinów używa się specjalistycznego sprzętu i oprogramowania, które zazwyczaj nie są
    pełnymi węzłami sieci.

DTO::
    Obiekt transferu danych (ang. Data Transfer Object) jest obiektem zawierającym zbiór danych, a także zapewniający
    wsparcie dla mechanizmów serializacji oraz deserializacji. Nie powinien zawierać żadnej logiki. Zazwyczaj
    używa się ich do transferu danych pomiędzy zdalnymi interfejsami. Dzięki temu uzyskuje się rozdzielenie
    pomiędzy obiektami domenowymi aplikacji a danymi zwracanymi przez sieć.
