[glossary]
== Słownik pojęć

multisig::
    Rozdaj adresu, który wymaga kilku podpisów cyfrowych, aby wykorzystać zapisane na nim środki. Jeżeli transakcja
    nie będzie podpisana przez wymaganą liczbę użytkowników, zostanie ona odrzucona przez inne węzły Bitcoina.
    <<btcbook>>

macaroon::
    Dane uwierzytelniające, które zapewniają elastyczne wsparcie dla kontrolowanego udostępniania w zdecentralizowanych
    rozproszonych systemach, takich jak sieć Lightning. Może on łączyć się z usługami i umożliwiać wykonywanie działań
    w imieniu węzła Lightning. Jest podobny do pliku cookie, ale w przeciwieństwie do tradycyjnego pliku cookie
    przeglądarki, można utworzyć makaronik o ograniczonych możliwościach, a następnie wysłać go do innych użytkowników.
    <<lnbook>>

UTXO::
    Jest to niewydane wyjście z transakcji Bitcoin. Suma wartości UTXO użytkownika mówi, ile posiada on Bitcoinów.

satoshi::
    Najmniejsza jednostka rozliczeniowa w ekosystemie Bitcoina. Można ją porównać do groszy w polskiej walucie.
    Jeden satoshi jest równowarte 0,00000001 BTC. Wszystkie operacje w sieci takie jak transakcje operują właśnie
    na wartości satoshi.
