[glossary]
== Słownik pojęć

multisig::
    Rozdaj adresu, który wymaga kilku podpisów cyfrowych, aby wykorzystać zapisane na nim środki. Jeżeli transakcja
    nie będzie podpisana przez wymaganą liczbę użytkowników, zostanie ona odrzucona przez inne węzły Bitcoina.
    <<btcbook>>

macaroon::
    Dane uwierzytelniające, które zapewniają elastyczne wsparcie dla kontrolowanego udostępniania w zdecentralizowanych
    rozproszonych systemach, takich jak sieć Lightning. Może on łączyć się z usługami i umożliwiać wykonywanie działań
    w imieniu węzła Lightning. Jest podobny do pliku cookie, ale w przeciwieństwie do tradycyjnego pliku cookie
    przeglądarki, można utworzyć makaronik o ograniczonych możliwościach, a następnie wysłać go do innych użytkowników.
    <<lnbook>>

Wyjście transakcji::
    Zawiera ono instrukcje, w jaki sposób wysłać środki w transakcji. Składa się między innymi z wartości wyjścia oraz
    skryptu blokującego środki. W skrypcie zazwyczaj zakodowany jest adres publiczny nowego właściciela środków.

Wejście transakcji::
    Jest to odniesienie do poprzedniego niewydanego wyjścia transakcji. Zawiera między innymi indeks, hash poprzedniej
    transakcji, z której pochodzi wyjście oraz skrypt odblokowujący środki. Ten ostatni zazwyczaj mieści podpis ECDSA
    oraz klucz publiczny właściciela wydawanego wyjścia. Jest to oczywiście zależne od typu transakcji.

UTXO::
    Jest to niewydane wyjście z transakcji Bitcoin. Suma wartości UTXO użytkownika mówi, ile posiada on Bitcoinów.

satoshi::
    Najmniejsza jednostka rozliczeniowa w ekosystemie Bitcoina. Można ją porównać do groszy w polskiej walucie.
    Jeden satoshi jest równowarte 0,00000001 BTC. Wszystkie operacje w sieci takie jak transakcje operują właśnie
    na wartości satoshi.

Węzeł sieci Bitcoin::
    Jest to program działający w sieci Bitcoina, który przechowuje, synchronizuje oraz sprawdza konsensus blockchaina.
    Wyróżniamy kilka rodzajów węzłów. Najczęściej spotyka się węzły pełne oraz niepełne (lekkie). Węzły pełne
    wyróżniają się tym, że przechowują kopię całego blockchaina.

Górnik::
    W kontekście sieci Bitcoin jest to program zajmujący się zbieraniem i walidacją transakcji, budowaniem bloków oraz
    liczeniem dla nich dowodu pracy. Za wykopanie bloku górnik otrzymuje nagrodę w postaci określonej liczby Bitcoinów.
    W tak zwanym "Bitcoin whitepaper <<whitepaper>>", słowo węzeł używane było jako synonim górnika, aczkolwiek
    współcześnie do kopania Bitcoinów używa się specjalistycznego sprzętu i oprogramowania, które zazwyczaj nie są
    pełnymi węzłami sieci.

DTO::
    Obiekt transferu danych (ang. Data Transfer Object) jest obiektem zawierającym zbiór danych, a także zapewniający
    wsparcie dla mechanizmów serializacji oraz deserializacji. Nie powinien zawierać żadnej logiki. Zazwyczaj
    używa się ich do transferu danych pomiędzy zdalnymi interfejsami. Dzięki temu uzyskuje się rozdzielenie
    pomiędzy obiektami domenowymi aplikacji a danymi zwracanymi przez sieć.

Dowód pracy::
    Jest to kryptograficzne potwierdzenie pokazujące, że jedna strona poświęciła pewien wysiłek obliczeniowy na
    określony cel. Jest to jedna z metod konsensusu wykorzystywana w kryptowalutach, w tym w Bitcoinie.
    Dowód pracy może zostać potwierdzony przez weryfikatorów przy minimalnym wysiłku z ich strony.

Mnemonic phrase::
    Standard pozwalający na eksport oraz import klucza publicznego zaprezentowany w standardzie BIP-39.
    _Mnemonic phrase_ składa się z 12 bądź 24 angielskich słów, które po przekształceniu tworzą ziarno generatora.
    Dzięki niemu można obliczyć wartość klucza prywatnego w sposób deterministyczny. Zapisanie sekwencji słów pozwala
    na późniejsze odtworzenie portfela, na przykład w przypadku utraty urządzenia.

Invoice::
    Rodzaj faktury, która służy do wykonywania płatności w sieci Lightning. Generowane są przez odbiorców
    płatności. Następnie _invoice_ musi zostać przekazany płatnikowi, aby ten mógł go opłacić. Każdy _invoice_ jest
    podpisany cyfrowo przez odbiorcę, a zawiera między innymi kwotę płatności, klucz publiczny odbiorcy, limit
    czasu na zapłatę oraz wspierane funkcjonalności Lightning.

REPL::
    _Read-eval-print-loop_ jest prostym środowiskiem, które pobiera wejście użytkownika, a następnie wykonuje je i
    wypisuje wynik. Wszystkie czynności odbywają się w pętli, co pozwala na szybkie wykonywanie poleceń bądź
    pojedynczych instrukcji kodu.

Hook::
    Funkcjonalność biblioteki React. Hooki to funkcje, które pozwalają używać stanu i innych funkcjonalności Reacta,
    bez użycia klas.
