[#_wstep]
== Wstęp

W ostatnich kilkunastu latach technologie blockchain i kryptowaluty zaliczyły ogromny wzrost
popularności. Wraz z dynamicznym rozwojem tych technologii pojawiły się również inne zastosowania
niż tylko wykorzystanie ich jako wirtualnych pieniędzy. Transakcje w kryptowalutach można traktować jako
niezmienne tokeny, a co za tym idzie użyć ich na przykład jako rodzaj certyfikatu dla różnych przedmiotów czy też
wydarzeń. Niestety pojedyncze transakcje w najpopularniejszych kryptowalutach są drogie, więc pojawia się problem
finansowania operacji. Celem naszego zespołu jest opracowanie rozwiązania, które umożliwiłoby finansowanie takich
certyfikatów.

Rozwiązaniem, które proponuje zespół projektowy, jest stworzenie serwera do przyjmowanie płatności w Bitcoinach z
wykorzystaniem sieci Lightning. Pozwala ona na zagregowanie wielu płatności do jednej transakcji w specjalnych kanałach
płatności, co pozwala obniżyć koszta. Przy każdej płatności użytkownik otrzyma unikatowy token, który będzie mógł
później wykorzystać u firmy zarządzającej serwerem płatności. Serwer będzie posiadał wbudowany portfel, na który będą
przelewane środki z sieci Lightning. Aby wprowadzić dodatkowe zabezpieczenie portfela, każda transakcja wychodząca
będzie musiała zostać podpisana przez wszystkie osoby do tego uprawnione za pomocą specjalnej aplikacji mobilnej.

Projekt powstanie z wykorzystanie nowoczesnych technologii takich jak _Java, Spring, TypeScript React_ i _React
Native_ z wykorzystaniem wysokiej jakości narzędzi oraz bibliotek. Zespół planuje pracować z wykorzystaniem metodyk
zwinnych, konkretnie używając iteracyjnych oraz przyrostowych ram postępowania _Scrum_. Celem jest stworzenie
lekkiego i skalowalnego rozwiązania, które każde przedsiębiorstwo będzie mogło wdrożyć i dostosować do swoich potrzeb
bez dużych nakładów pracy. Członkowie zespołu chcieliby również, aby udało się wdrożyć projekt w ramach europejskiego
projektu _iNGENIOUS IoC_.
