name: Documents CI
on:
  push:
    branches: [ dev ]
  pull_request:
    paths:
      - 'docs/**'

defaults:
  run:
    working-directory: docs

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install dependencies
        run: |
          gem install asciidoctor
          gem install asciidoctor-pdf
          gem install asciidoctor-diagram
          gem install rouge
      - name: Install pdftk
        run: sudo apt-get install -y pdftk
      - name: Build files
        run: make
      - name: Line endings check
        run: git grep -n --color $'\r' -- "*.adoc" && echo "^ Possible Windows style line ending detected. Please use Unix style line endings (\n)." && exit 1 || true
      - name: Find trailing spaces
        run: git grep -n --color ' $' -- "*.adoc" && echo "^ Trailing space detected at end of line. Please remove." && exit 1 || true
      - name: Check for tabs
        run: git grep  -n --color  $'\t' -- "*.adoc" && echo "^ Use of tabs detected. Please use space for indentation." && exit 1 || true
      - name: Multiple blank lines
        run: git grep "" -- "*.adoc" | uniq -c | grep -1 "^      [2-9] " | cut -b9- | sed 's/:$/:[more-than-one-blank-line-here-please-remove]/' | grep ":" && echo "^ Multiple blank lines detected. Please use only one blank line between paragraphs." && exit 1 || true
      - name: File should end with new line
        run: for FILE in $(git ls-files -- "*.adoc"); do if [[ $(tail -c1 $FILE) != "" ]]; then echo "File ${FILE} does not end with a newline character (\n)."; exit 1; fi; done
      - name: Max line width
        run: git grep -n --color -P '^(?!include).{121}' -- "*.adoc" && echo "^ Lines should not be longer than 120 characters" && exit 1 || true
