name: E2E tests

on:
  push:
  pull_request:
    paths:
      - 'webapp/**'
      - 'webservice/**'

defaults:
  run:
    working-directory: webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: webapp/yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: webapp
          install: false
          start: yarn setup:docker:regtest, yarn setup:backend, yarn dev
          wait-on: http://localhost:8080, http://localhost:3000
