name: E2E tests

on:
  push:
  pull_request:
    paths:
      - 'webapp/**'
      - 'webservice/**'

defaults:
  run:
    working-directory: webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          install-command: yarn install
          start: yarn setup:docker:regtest, yarn setup:backend, yarn dev
          wait-on: http://localhost:8080, http://localhost:3000
