name: React Native mobileapp CI

on:
  push:
    branches: [dev]
  pull_request:
    paths:
      - 'mobileapp/**'

defaults:
  run:
    working-directory: mobileapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: mobileapp/yarn.lock

      - name: Build common package
        working-directory: common-ts
        run: yarn && tsc
      - name: Install dependencies
        run: yarn
      - name: Eslint
        run: yarn lint
      - name: Run tests
        run: yarn test
