# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React webapp CI

on:
  push:
    branches: [ dev ]
  pull_request:
    paths:
      - 'webapp/**'

defaults:
  run:
    working-directory: webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: webapp/yarn.lock

      - name: Install dependencies
        run: yarn
      - name: Eslint
        run: yarn lint
      - name: Tests
        run: yarn test:unit
      - name: Typescript and build
        run: yarn build
      - name: Test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: webapp-test-report
          path: webapp/test-report.html
