name: Java webservice CI
on:
  push:
    branches: [dev]
    pull_request:

defaults:
  run:
    working-directory: webservice

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Compile
        run: mvn compile
      - name: Run Tests
        run: mvn -B test
      - name: Code coverage
        run: mvn -B verify -P test-coverage
